version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
